DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employee;



CREATE TABLE roles (
  role_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  job_title VARCHAR(30) NOT NULL,
  salary DECIMAL(7,2) NOT NULL,
  CONSTRAINT fk_party FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
);

CREATE TABLE department (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  department_name VARCHAR(30) NOT NULL
);


CREATE TABLE employee (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  CONSTRAINT fk_party FOREIGN KEY (job_title) REFERENCES roles(id) ON DELETE SET NULL,
  CONSTRAINT fk_party FOREIGN KEY (department_name) REFERENCES department(id) ON DELETE SET NULL,
  CONSTRAINT fk_party FOREIGN KEY (salary) REFERENCES roles(id) ON DELETE SET NULL,
  CONSTRAINT fk_party FOREIGN KEY (manager_id) REFERENCES roles(id) ON DELETE SET NULL
);

